// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Friendship struct {
	UserID   int64     `json:"user_id"`
	FriendID int64     `json:"friend_id"`
	RoomID   int64     `json:"room_id"`
	Status   string    `json:"status"`
	CreateAt time.Time `json:"create_at"`
}

type Message struct {
	ID       int64     `json:"id"`
	RoomID   int64     `json:"room_id"`
	SenderID int64     `json:"sender_id"`
	Content  string    `json:"content"`
	Kind     string    `json:"kind"`
	SendAt   time.Time `json:"send_at"`
}

type Room struct {
	ID       int64     `json:"id"`
	Name     string    `json:"name"`
	Cover    string    `json:"cover"`
	Category string    `json:"category"`
	CreateAt time.Time `json:"create_at"`
}

type RoomMember struct {
	RoomID   int64     `json:"room_id"`
	MemberID int64     `json:"member_id"`
	Rank     string    `json:"rank"`
	JoinAt   time.Time `json:"join_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       int64     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	ClientIp     string    `json:"client_ip"`
	UserAgent    string    `json:"user_agent"`
	ExpireAt     time.Time `json:"expire_at"`
	CreateAt     time.Time `json:"create_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	Avatar         string    `json:"avatar"`
	Nickname       string    `json:"nickname"`
	Role           string    `json:"role"`
	RoomID         int64     `json:"room_id"`
	Deleted        bool      `json:"deleted"`
	CreateAt       time.Time `json:"create_at"`
}
