// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFriend(ctx context.Context, arg CreateFriendParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateRoomMember(ctx context.Context, arg CreateRoomMemberParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFriend(ctx context.Context, arg DeleteFriendParams) ([]int64, error)
	DeleteFriendByUser(ctx context.Context, id int64) ([]int64, error)
	DeleteMember(ctx context.Context, arg DeleteMemberParams) error
	DeleteMemberByRoom(ctx context.Context, roomID int64) error
	DeleteMemberByUser(ctx context.Context, arg DeleteMemberByUserParams) error
	DeleteMessageByUser(ctx context.Context, arg DeleteMessageByUserParams) error
	DeleteRooms(ctx context.Context, roomIds []int64) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	DeleteSessionByUser(ctx context.Context, userID int64) error
	DeleteUser(ctx context.Context, id int64) ([]int64, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
